package org.appland.settlers.model;

public enum BorderChangeCause {
    MILITARY_BUILDING_OCCUPIED,
    MILITARY_BUILDING_UPGRADED,
    MILITARY_BUILDING_TORN_DOWN,
    NEW_SETTLEMENT,
    MILITARY_BUILDING_CAPTURED
}
