package org.appland.settlers.model;

public enum Material {

    SWORD, SHIELD, PRIVATE, GENERAL, SERGEANT, BEER, GOLD, WOOD, PLANCK, STONE, 
    WHEAT, COURIER, FORESTER, WOODCUTTER_WORKER, STONEMASON, FARMER, SAWMILL_WORKER, 
    WATER, WELL_WORKER, FLOUR, MILLER
}
