package org.appland.settlers.model;

public enum WorkerAction {
    CUTTING,
    HACKING_STONE,
    PLANTING_WHEAT,
    FISHING,
    INVESTIGATING,
    HARVESTING,
    HAMMERING_HOUSE_HIGH_AND_LOW,
    PLANTING_TREE,
    BAKING,
    DIGGING_AND_STOMPING,
    DRINKING_BEER,
    INSPECTING_HOUSE_CONSTRUCTION,
    PICKING_UP_MEAT,
    SAWING,
    SHOOTING
}
