package org.appland.settlers.maps;

import org.appland.settlers.model.DecorationType;

import java.util.HashMap;
import java.util.Map;

import static org.appland.settlers.model.DecorationType.*;

public class Translator {
    public static final Map<Integer, DecorationType> DEFAULT_OBJECT_PROPERTY_TO_DECORATION_MAP = Map.ofEntries(
            Map.entry(0x00, MINI_BROWN_MUSHROOM),
            Map.entry(0x01, TOADSTOOL),
            Map.entry(0x02, MINI_STONE),
            Map.entry(0x03, SMALL_STONE),
            Map.entry(0x04, STONE),
            Map.entry(0x05, DEAD_TREE_LYING_DOWN),
            Map.entry(0x06, DEAD_TREE),
            Map.entry(0x07, ANIMAL_SKELETON_1),
            Map.entry(0x08, ANIMAL_SKELETON_2),
            Map.entry(0x09, FLOWERS),
            Map.entry(0x0A, LARGE_BUSH_1),
            Map.entry(0x0B, PILE_OF_STONES),
            Map.entry(0x0C, CACTUS_1),
            Map.entry(0x0D, CACTUS_2),
            Map.entry(0x0E, CATTAIL_1),
            Map.entry(0x0F, CATTAIL_2),
            Map.entry(0x10, LARGE_BUSH_2),
            Map.entry(0x11, BUSH_3),
            Map.entry(0x12, SMALL_BUSH),
            Map.entry(0x13, CATTAIL_3),
            Map.entry(0x14, CATTAIL_4),
            Map.entry(0x16, PORTAL),
            Map.entry(0x17, SHINING_PORTAL),
            Map.entry(0x22, BROWN_MUSHROOM),
            Map.entry(0x23, MINI_STONE_WITH_GRASS),
            Map.entry(0x24, SMALL_STONE_WITH_GRASS),
            Map.entry(0x25, SOME_SMALL_STONES_1),
            Map.entry(0x26, SOME_SMALL_STONES_2),
            Map.entry(0x27, SOME_SMALL_STONES_3),
            Map.entry(0x28, SPARSE_BUSH),
            Map.entry(0x29, SOME_WATER),
            Map.entry(0x2A, LITTLE_GRASS),
            Map.entry(0x2B, SNOWMAN));
    public static final Map<Integer, DecorationType> MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();
    public static final Map<Integer, DecorationType> MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();
    public static final Map<Integer, DecorationType> MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();
    public static final Map<Integer, DecorationType> MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();
    public static final Map<Integer, DecorationType> MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();
    public static final Map<Integer, DecorationType> MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP = new HashMap<>();

    static {

        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, STRANDED_SHIP);

        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1B, TENT_HEADQUARTERS);

        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, STRANDED_SHIP);

        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2F, TENT_HEADQUARTERS);

        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, STRANDED_SHIP);
        MIS0BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, STRANDED_SHIP);

        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x19, SHARP_STONES_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1A, SHARP_STONES_3);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1B, SHARP_STONES_4);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1C, SHARP_STONES_5);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1D, SHARP_STONES_6);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1E, SHARP_STONES_7);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1F, DEAD_TREE_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x20, DEAD_TREE_3);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x21, SKELETON_TUNNEL);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2D, SHARP_STONES_2);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2E, SHARP_STONES_3);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2F, SHARP_STONES_4);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x30, SHARP_STONES_5);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, SHARP_STONES_1);
        MIS1BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, SHARP_STONES_1);

        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x19, GUARDHOUSE_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1A, WATCHTOWER_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1B, FORTRESS_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1C, SOLDIER_SKELETON);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1D, SHARP_STONES_6);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1E, SHARP_STONES_7);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1F, DEAD_TREE_2);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x20, DEAD_TREE_3);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x21, SKELETON_TUNNEL);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2D, GUARDHOUSE_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2E, WATCHTOWER_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2F, FORTRESS_RUIN);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x30, SOLDIER_SKELETON);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, TENT);
        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, TENT);

        MIS2BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x38, TENT);

        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, SMALL_VIKING_WITH_BOAT);

        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, SMALL_VIKING_WITH_BOAT);

        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, SMALL_VIKING_WITH_BOAT);
        MIS3BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, SMALL_VIKING_WITH_BOAT);

        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, SCROLLS);

        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, SCROLLS);

        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, SCROLLS);
        MIS4BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, SCROLLS);

        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x00, MINI_BROWN_MUSHROOM);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x01, TOADSTOOL);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x02, MINI_STONE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x03, SMALL_STONE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x04, STONE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x05, DEAD_TREE_LYING_DOWN);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x06, DEAD_TREE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x07, ANIMAL_SKELETON_1);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x08, ANIMAL_SKELETON_2);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x09, FLOWERS);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0A, LARGE_BUSH_1);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0B, PILE_OF_STONES);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0C, CACTUS_1);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0D, CACTUS_2);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0E, CATTAIL_1);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x0F, GRASS_1);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x10, BUSH);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x11, SMALL_BUSH);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x12, MINI_BUSH);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x13, GRASS_2);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x14, MINI_GRASS);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x15, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x16, PORTAL);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x17, SHINING_PORTAL);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x18, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x19, WHALE_SKELETON_HEAD_LEFT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1A, CAVE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x1B, SMALL_VIKING_WITH_BOAT);

        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x22, BROWN_MUSHROOM);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x23, MINI_STONE_WITH_GRASS);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x24, SMALL_STONE_WITH_GRASS);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x25, SOME_SMALL_STONES);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x26, SOME_SMALLER_STONES);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x27, FEW_SMALL_STONES);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x28, SPARSE_BUSH);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x29, SOME_WATER);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2A, LITTLE_GRASS); // VERIFY
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2B, SNOWMAN);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2C, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2D, WHALE_SKELETON_HEAD_LEFT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2E, CAVE);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x2F, SMALL_VIKING_WITH_BOAT);

        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x31, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x32, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x33, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x34, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x35, WHALE_SKELETON_HEAD_RIGHT);
        MIS5BOBS_OBJECT_PROPERTY_TO_DECORATION_MAP.put(0x36, WHALE_SKELETON_HEAD_RIGHT);
    }
}
