package org.appland.settlers.rest.resource;

public enum Command {
    PLACE_FLAG,
    PLACE_ROAD,
    PLACE_BUILDING,
    REMOVE_ROAD,
    REMOVE_FLAG,
    REMOVE_BUILDING,
    CALL_SCOUT,
    CALL_GEOLOGIST,
    FULL_SYNC,
    INFORMATION_ON_POINTS,
    SET_RESERVED_IN_HEADQUARTERS,
    START_DETAILED_MONITORING,
    STOP_DETAILED_MONITORING,
    REMOVE_MESSAGE, SET_COAL_QUOTAS, GET_COAL_QUOTAS, GET_FOOD_QUOTAS, SET_FOOD_QUOTAS, GET_WHEAT_QUOTAS, SET_WHEAT_QUOTAS, PLACE_FLAG_AND_ROAD
}
